CascadingDDL/Models/DBEntities/City.cs
namespace CascadingDDL.Models.DBEntities
{
    public class City
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public State State { get; set; }
    }
}

CascadingDDL/Models/DBEntities/Country.cs
namespace CascadingDDL.Models.DBEntities
{
    public class Country
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CountryCode { get; set; }
        
    }
}

CascadingDDL/Models/DBEntities/State.cs
namespace CascadingDDL.Models.DBEntities
{
    public class State
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Country Country { get; set; }
    }
}

CascadingDDL/Models/ErrorViewModel.cs
namespace CascadingDDL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CascadingDDL/Controllers/CascadingController.cs
using CascadingDDL.DAL;
using CascadingDDL.Models.DBEntities;
using Microsoft.AspNetCore.Mvc;

namespace CascadingDDL.Controllers
{
    public class CascadingController : Controller
    {
        private MyAppDBContext _context;

        public CascadingController(MyAppDBContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        public JsonResult GetCountries()
        {
            var countries = _context.Country.OrderBy(x => x.Name).ToList();
            return new JsonResult(countries);
        }
        public JsonResult GetStates(int id)
        {
            var states = _context.State.Where(x=>x.Country.Id ==id).OrderBy(x=>x.Name).ToList();
            return new JsonResult(states);
        }
        public JsonResult GetCities(int id)
        {
            var cities = _context.City.Where(x=>x.State.Id==id).OrderBy(x=>x.Name).ToList();    
            return new JsonResult(cities);
        }
    }
}

CascadingDDL/Controllers/HomeController.cs
using CascadingDDL.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CascadingDDL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CascadingDDL/Views/Cascading/Index.cshtml
@{
	ViewData["Title "] = "Cascading Drop Down List";
}
<h2>@ViewData["Title"]</h2>
<hr/>
<div class="container">
	<div class="card border-primary">
		<div class="card-header fw-bold border-primary">
			Cascading DDL
		</div>
		<div class="row">
			<div class="col-10 offset-1">
				<form>
					<div class="mb-2">
						<label>Country</label>
						<select id="country"class="form-control"></select>
					</div>
					<div class="mb-2">
						<label>State</label>
						<select id="state" class="form-control"></select>
					</div>
					<div class="mb-2">
						<label>City</label>
						<select id="city" class="form-control"></select>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@* <a href="~/lib/jquery/dist/jquery.min.map">~/lib/jquery/dist/jquery.min.map</a> *@
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/CascadingDDL.js"></script>

CascadingDDL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CascadingDDL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CascadingDDL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CascadingDDL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CascadingDDL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cascading" asp-action="Index">Cascading DDL</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CascadingDDL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>